### ISSUE TITLE
Conents.swift is missing

### ISSUE THREAD

**Issue by zolomatok** [krzysztofzablocki/Swift-Observable#1]
When I download the playground as a **zip** from GitHub and try to open it in Xcode, it throws the error **"Playground file is missing a "Contents.swift" file."** and won't open the playground.

**Comment by krzysztofzablocki** [comment]
it's from 2014 so both swift and playgrounds changed a lot since then, code is here https://github.com/krzysztofzablocki/Swift-Observable/blob/master/Observer.playground/section-1.swift

**Comment by zolomatok** [comment]
Oh, thanks! I'll check it out.
